name = "BEAN"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liryXiyuD91M1f2h"
GITHUB_OWNER = "pcbean"
GITHUB_REPO = "MainPage_NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://page.908203.xyz/api/auth"
NEXT_PUBLIC_API_URL="https://page.908203.xyz"

